#!/bin/bash
#<Konrad><<Dzień>
#Zadanie 04 :
#Numerowanie wszystkich plików w zadanym katalogu (parametr wywołania skryptu), do których
#mamy ustawione prawo wykonywania ("execute"), przez dodanie dodatkowego członu rozszerzenia
#o postaci .numerkolejny. Numeracja powinna przebiegać wedługo wielkości plików


licznik=0

for file in $(ls -S)
do
	if [ -x "${file}" ]
	then
		mv "${file}" "${file}.${licznik}"
		((licznik++))
	fi
done
