#!/usr/bin/perl -w

# w zadanym drzewie katalogow usunac dowiazania symboliczne wskazujace poza drzewo


use Cwd qw(abs_path realpath);
use File::Spec::Functions qw( rel2abs canonpath );
use File::Find;
use File::Basename;


next unless @ARGV == '1';
$dir = realpath($ARGV[0]);

find(\&my_func, $dir);

sub my_func
{
    my $file = "$File::Find::name";
    return unless -l $file;
    $target = abs_path(readlink("$file"));
    print rel2abs(readlink("$file"));
    print "\n";
    print "$target \n";
    my($f, $d, $e) = fileparse($target);
    $fname = $f.$e;

    $lastChr = substr($fname, -1);
    $firstChr = substr($fname, 0, 1);

    if ($firstChr eq $lastChr) {
      print "$fname \n";
    }

}
